import { z } from "zod";

export const BUSINESS_LINES = [
  "Yacht",
  "Property",
  "Marine Cargo (Reefer/GFS)",
  "Marine Cargo (Non-Reefer)",
  "Bulk Vessel",
  "Air Shipment (NET)",
  "Fidelity Claims",
  "Other / Requires Review",
];

export const DOCUMENT_TYPES = [
  "Policy",
  "Claim Form",
  "Supporting Evidence",
  "Survey Report",
  "Photographs",
  "Commercial Invoice",
  "Repair Invoice or Quotation",
  "Packing List",
  "Bill of Lading",
  "Air Waybill",
  "Truck Waybill",
  "Temperature Records",
  "Cargo Certificate",
  "Notice of Claim",
  "Incident Report",
  "Registration",
  "Employee Records",
  "Account Ledger",
  "Investigation Statement",
  "Correspondence",
  "Other",
];

export const CLAIM_FIELDS = [
  "applicant",
  "insured",
  "insurer",
  "reassured",
  "reinsurer",
  "broker",
  "claim_reference",
  "policy_number",
  "policy_period",
  "policy_inception_date",
  "policy_issue_date",
  "policy_terms",
  "policy_limit",
  "policy_premium",
  "insured_value",
  "valuation_basis",
  "valuation_uplift_percent",
  "valuation_uplift_amount",
  "deductible",
  "date_of_loss",
  "date_of_intimation",
  "cause_of_loss",
  "country",
  "currency",
  "claim_amount",
  "gross_claim_amount",
  "invoice_total",
  "freight_amount",
  "insurance_amount",
  "fob_value",
  "freight_invoice_total",
  "fees_amount",
  "salvage_amount",
  "recovery_amount",
  "depreciation_amount",
  "adjusted_amount",
  "surveyor",
  "vessel_name",
  "voyage_number",
  "transshipment_port",
  "feeder_vessel",
  "feeder_voyage",
  "container_number",
  "port_of_loading",
  "port_of_discharge",
  "commodity",
  "shipper",
  "consignee",
  "carrier",
  "air_waybill",
  "bill_of_lading",
  "invoice_number",
  "freight_invoice_number",
  "invoice_date",
  "packing_list_number",
  "packing_list_date",
  "freight_invoice_date",
  "purchase_order",
  "voyage_from",
  "voyage_to",
  "container_numbers",
  "quantity",
  "net_weight",
  "gross_weight",
  "conveyance_mode",
  "country_of_origin",
  "destination_country",
  "incoterm",
  "departure_date",
  "arrival_date",
  "shipment_date",
  "delivery_date",
  "discharge_date",
  "damage_report_date",
  "notice_date",
  "destruction_date",
  "seal_numbers",
  "seal_condition",
  "production_dates",
  "expiry_dates",
  "affected_container",
  "affected_quantity",
  "shortage_breakdown",
  "survey_attendance_scope",
  "salvage_quantity",
  "total_loss_quantity",
  "temperature_requirement",
  "temperature_findings",
  "survey_date",
  "survey_location",
  "damage_findings",
  "interest_insured",
  "appointment_details",
  "warranties_conditions",
  "insurable_interest",
  "adequacy_of_insured_value",
  "claim_basis",
  "salvage_findings",
  "recovery_findings",
];

export const EVIDENCE_MODES = ["extracted_text", "document_vision", "image_vision"];

const sourceSchema = z.object({
  document_id: z.string(),
  document_name: z.string(),
  page: z.number().int().positive().nullable(),
  supporting_text: z.string(),
  confidence: z.number().min(0).max(1),
  evidence_mode: z.preprocess(
    (value) => value ?? "extracted_text",
    z.enum(EVIDENCE_MODES),
  ),
});

const coerceStringOrNull = (value) => (value === null || value === undefined ? null : String(value));
const coerceString = (value) => (value === null || value === undefined ? "" : String(value));

const fieldSchema = z.object({
  field: z.enum(CLAIM_FIELDS),
  value: z.preprocess(coerceStringOrNull, z.string().nullable()),
  normalized_value: z.preprocess(coerceStringOrNull, z.string().nullable()),
  confidence: z.number().min(0).max(1),
  requires_confirmation: z.boolean(),
  sources: z.array(sourceSchema),
});

const adjustmentLineItemSchema = z.object({
  description: z.preprocess(coerceString, z.string()),
  quantity: z.preprocess(coerceStringOrNull, z.string().nullable()),
  unit_price: z.preprocess(coerceStringOrNull, z.string().nullable()),
  adjusted_value: z.preprocess(coerceString, z.string()),
  currency: z.preprocess(coerceStringOrNull, z.string().nullable()),
  basis: z.preprocess(coerceString, z.string()),
  confidence: z.number().min(0).max(1),
  sources: z.array(sourceSchema),
});

export const claimAnalysisSchema = z.object({
  classification: z.object({
    business_line: z.enum(BUSINESS_LINES),
    confidence: z.number().min(0).max(1),
    rationale: z.string(),
    sources: z.array(sourceSchema),
  }),
  document_types: z.array(z.object({
    document_type: z.enum(DOCUMENT_TYPES),
    confidence: z.number().min(0).max(1),
    sufficient_information: z.boolean(),
    rationale: z.string(),
    sources: z.array(sourceSchema),
  })),
  fields: z.array(fieldSchema),
  adjustment_line_items: z.array(adjustmentLineItemSchema),
  missing_documents: z.array(z.object({
    document_type: z.enum(DOCUMENT_TYPES),
    reason: z.string(),
    missing_information: z.array(z.string()),
  })),
  evidence_findings: z.array(z.object({
    finding: z.string(),
    confidence: z.number().min(0).max(1),
    sources: z.array(sourceSchema),
  })),
  summary: z.string(),
  warnings: z.array(z.string()),
  human_review_required: z.array(z.string()),
});

export const sourceSchemaForTests = sourceSchema;
